### PR TITLE
Add support for vue files

### PR DESCRIPTION
**Pull request by patrick91**

### CODE REVIEW

**Comment by patrick91** [comment]
@shinnn do you have any feedback for this?

**Comment by valtermro** [comment]
@patrick91 You think it would be better to use `html` instead of `vue`?
I made a few tests and by adding html to the list of supported languages I got this extension working with both `.vue` and `.html` files. Also, by adding support for html files this PR could close https://github.com/shinnn/vscode-stylelint/issues/52.
Sorry if I'm doing I shouldn't by commenting here.

**Comment by patrick91** [comment]
@valtermro thanks for the comment! yeah, it could be better to use html, but I think shinnn is really busy. I don't think this is going to be merged soon :(

**Comment by tiagofscoelho** [comment]
+1

**Comment by rmartins90** [comment]
👍

**Comment by shinnn** [comment]
Fixed via https://github.com/shinnn/vscode-stylelint/commit/9f504667964140336b841a7f7ba55d728488739d

**Pull request closed without merging**
