### PR TITLE
Add Support for Stylus

### PR DESCRIPTION
**Pull request by tannerhodges**
Adds an activationEvent so stylelint can run in Stylus files.

Fixes https://github.com/shinnn/vscode-stylelint/issues/41

### CODE REVIEW

**Comment by shinnn** [comment]
Have you really read https://github.com/shinnn/vscode-stylelint/issues/41?

**Comment by tannerhodges** [comment]
Yes, sorry I should've explained:

While stylelint doesn't _fully_ support Stylus syntax (e.g., variables), it does still parse Stylus files as CSS and can be used to lint standard issues (e.g., hex values, empty blocks, duplicate selectors).

For example, here's a reduced Stylus project with stylelint configured to lint recommended issues (disabling options that aren't supported yet): https://github.com/tannerhodges/stylus-example

If you enable vscode-stylelint for Stylus files (I tested by modifying `vim ~/.vscode/extensions/shinnn.stylelint-0.43.0/package.json `) it correctly highlights syntax errors like this:

screenshot 2018-09-19 13 50 02

Even though full Stylus syntax support hasn't arrived yet, it would be great if we enabled the features stylelint does make available in VS Code by default.

Appreciate you taking the time to review this.

**Comment by shinnn** [comment]
I'm going to pass on this, because stylelint fails to parse this simple Stylus source.

__fixture.styl__

```stylus
v = 1px

a
  font v
```

__run.js__

```js
'use strict';

const {lint} = require('stylelint');

(async () => {
  process.stdout.write((await lint({
    files: ['fixture.styl'],
    formatter: 'string',
    config: {
      rules: {}
    }
  })).output);
})();

```

```console
$ node run.js

fixture.styl
 1:1  ✖  Unknown word   CssSyntaxError
```

https://github.com/stylelint/stylelint/issues/674 still needs to be fixed before merging this change.

**Comment by tannerhodges** [comment]
I understand.

Is there another way to activate vscode-stylelint for Stylus files?

For example, in Sublime Text I used [SublimeLinter's `selector` option](http://www.sublimelinter.com/en/stable/linter_settings.html#selector) to enable stylelint for different file types:

```js
// SublimeLinter Settings - User
{
  "linters": {
    "stylelint": {
      "selector": "source.css, source.scss, source.stylus"
    }
  }
}
```

I'd love to find a similar option in VS Code.

Thanks again for your help.

**Comment by shinnn** [comment]
No.

**Pull request closed without merging**
