### PR TITLE
Proposal: Update icons

### PR DESCRIPTION
**Pull request by abdonrd**
Using the [stylelint identity icon](https://github.com/stylelint/stylelint/tree/master/identity).

### CODE REVIEW

**Comment by shinnn** [comment]
There seems to be a loose convention to use a circle icon for VSCode extensions, https://marketplace.visualstudio.com/search?target=VSCode&category=Linters&sortBy=Downloads, and I'd like to follow that.

**Comment by abdonrd** [comment]
Updated with @shinnn comments, thanks!

**Comment by abdonrd** [comment]
Updated with @shinnn comments, thanks!

**Comment by shinnn** [comment]
After a deep consideration, I decided to decline to this proposal because of the very simple reason; mine is better.

The official one explains nothing to users. I guess 99.999 % of people in the world cannot recognize the tuxedo icon as a CSS lint tool.

Language is one of the greatest invention of human being. It often illustrate things better than an icon does.

If the stylelint team improves their icon, I'll of course reconsider switching to the official icon.

Anyway thanks for taking this up for a discussion, @abdonrd :)

**Pull request closed without merging**
