### PR TITLE
Allow extension to be activated on all events

### LINKED ISSUE #124: Plugin activation for Vue components
Hi!

Currently, this plugin does not get activated when a Vue component written according to this [spec](https://vue-loader.vuejs.org/en/start/spec.html) is opened in vscode. The plugin should get activated since there is a style tag in these component files.

Even though the plugin configuration `stylelint.additionalDocumentSelectors` allows for adding the `vue` option, we still need to open up a file with type that is listed in the plugin's activation event to activate the plugin, and only then get the plugin to work on `*.vue` files.

My idea to resolve this is to either:

* Append `workspaceContains:node_modules/vue-loader/package.json` to the plugin's activation event.

* Use `*` instead in plugin's activation event. The `documentSelector` key in the extension will take care of when the plugin will get used, based on the file type

### PR DESCRIPTION
**Pull request by Raphx**
A PR for the second approach as mentioned in #124 

Closes #124

### CODE REVIEW

**Comment by shinnn** [comment]
@Raphx Do you know any downsides of this change? The one I could imagine is that the stylelint extension server meaninglessly starts running even if the current project doesn't include any CSS files. I don't know whether it can be said considerable regression, though.

**Comment by Raphx** [comment]
Apart from the extension startup time, I don't think there are any grave impacts on performance. Since the extension allows user to add additional document selectors, this option is by far the most flexible to allow user's customization.

Another idea that I just thought of, is to add a command for the extension, and use command invocation as the activation event, i.e. using something like `onCommand:extension.activateStylelint` instead of `*` for the activation event. This means user would need to explicitly invoke the command to activate the extension. This would be the balance between not having unnecessary server startup, and flexible extension customization. 😉

**Comment by shinnn** [comment]
I finally decided to merge https://github.com/shinnn/vscode-stylelint/commit/c554d7afa6e2f3af7bb4dd5b09d14206ced72883. I'll reconsider switching to this `*` solution when it is really needed, though.

Thanks for the suggestion and taking time to create this pull request, @Raphx.

**Comment by Raphx** [comment]
Thank you @shinnn for the follow-up :)

**Pull request closed without merging**
