### PR TITLE
Add support for customizing the documents types that you would want to use stylelint with

### PR DESCRIPTION
**Pull request by orta**
Yes the line is wrong, but that's an issue with the CLI, not the extension.

screen shot 2017-06-27 at 14 22 07

I saw in #77 and #48 that people are opting for pretty large impact when opting in to CSS-in-JS.

I wanted to add Typescript support, so instead opted to allow letting the project define what document scopes they should have stylelint applied to. This means JS/TS/Vue and one's I've not thought of can be applied.

I also added an additional launch scope if you have installed  `stylelint-processor-styled-components` by looking for `node_modules/stylelint-processor-styled-components/package.json`. This means the language server won't start running for projects without the dependency it relies on.

### CODE REVIEW

**Comment by shinnn** [comment]
Included in v0.26.0. Thanks, @orta !

**Comment by shinnn** [comment]
Hi, @orta. Can you try using the latest version of this extension?

From v0.35.0 onward, this extension detects whether [stylelint-processor-styled-component](https://github.com/styled-components/stylelint-processor-styled-components) is installed or not, then automatically validates JavaScript files if it's installed.

Therefore, I'm planning to remove no longer needed `additionalDocumentSelectors` option and I'd like to hear your opinion about it.

**Comment by orta** [comment]
Hi @shinnn - when I update it and run my project, I  get

screen shot 2018-03-22 at 7 54 08 am

Which implies it can't find the line I think

**Comment by shinnn** [comment]
Hmm, interesting. I've never encountered the former error.

I’ll look into it.

**Comment by shinnn** [comment]
I found that [the undefined `line` problem is reproducible with any stylelint interfaces](https://github.com/styled-components/stylelint-processor-styled-components/issues/178). It's not a vscode-stylelint specific issue but more like a bug of stylelint-processor-styled-components.

@orta I think we can safely remove support for `additionalDocumentSelectors`.

**Comment by orta** [comment]
👍 cool, yep

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/commit/ec1609458a103f670acdc782a82a7d26c34657c3

**Pull request merged**
